### ISSUE TITLE
Divide CV section into columns

### ISSUE THREAD

**Issue by GustavoBerumen** [GustavoBerumen/gustavoberumen.github.io#7]
Please format of the text similar to the CV pdf as two columns 

<img width="1486" alt="Screenshot 2024-07-31 at 17 01 28" src="https://github.com/user-attachments/assets/f3fda69f-c7a3-4b75-bdde-1fdc5d049544">

**Comment by TuringTested** [comment]
![image](https://github.com/user-attachments/assets/45626779-1e85-4bc3-837f-59e5ead16496)
As you can see, there are a few differences between this and your pdf—particularly the horizontal lines seem not to appear, probably due to class inheritance in the CSS. I'll keep working on it.

**Comment by TuringTested** [comment]
The status of the layout is far more similar to that of the pdf. I'll await further instruction in terms of changes.
![image](https://github.com/user-attachments/assets/ef15c5c5-605f-47ff-8365-00f114cfe449)
I could start putting in the data in the same way you have it on your pdf, if you like.

**Comment by TuringTested** [comment]
Fixed layout on macOS

**Comment by TuringTested** [comment]
Updated information and format to be more similar to the PDF, and added button to top of page for easy access. Not sure how to make "relevant experience" etc. appear on one line or make the description span the second two columns, so formatting work still outstanding.
